version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gamification
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - 'default'
  server:
    build: ./images/server/
    depends_on:
       - db
    ports:
      - "8080:8080"
    links:
      - db